[project]
name = "screenbanter"
version = "0.1.0"
description = "Make your screen talk back. A DIY project built with VIBES to bridge Google’s Gemini Vision with Microsoft’s VibeVoice-0.5B for real-time desktop narration."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
    { name = "Alfred T", email = "" }
]
dependencies = [
    "google-generativeai",
    "uvicorn",
    "fastapi",
    "dxcam",
    # "pyaudio", # Requires Microsoft Visual C++ Build Tools
    # "pystray", # Also requires Visual C++ Build Tools, or has other native dependencies
    "global_hotkeys",
    "Nuitka",
    "numpy",
    "Pillow",
    "requests",
    "python-dotenv",
    "huggingface-hub",
    "torch==2.5.1",
    "torchvision==0.20.1",
    "torchaudio==2.5.1",
    "accelerate==1.6.0",
    "transformers==4.51.3",
    "llvmlite>=0.40.0",
    "numba>=0.57.0",
    "diffusers",
    "scipy",
    "librosa",
    "ml-collections",
    "absl-py",
    "av",
    "google-genai>=1.56.0",
    "pyaudio>=0.2.14",
]

[project.optional-dependencies]
dev = [
    "black",
    "ruff",
    "mypy",
    "pytest",
    "pre-commit"
]
